openapi: 3.1.0
info:
  title: Todo API - Protected Tasks
  description: Task endpoints secured with JWT and ownership checks
  version: 1.0.0

servers:
  - url: http://localhost:8000
    description: Local server

tags:
  - name: Tasks
    description: Protected task operations (JWT required)

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  responses:
    UnauthorizedError:
      description: Missing or invalid JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Not authenticated"
    ForbiddenError:
      description: Authenticated but not allowed (cross-user)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Forbidden: Task does not belong to the authenticated user"
    NotFoundError:
      description: Task not found for this user
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          example:
            detail: "Task 123 not found"
  schemas:
    ErrorResponse:
      type: object
      required: [detail]
      properties:
        detail:
          type: string
        error_code:
          type: string
          nullable: true

paths:
  /api/tasks:
    get:
      tags: [Tasks]
      summary: List tasks (JWT required)
      security: [{ BearerAuth: [] }]
      parameters:
        - in: query
          name: completed
          schema:
            type: boolean
          required: false
          description: Filter by completion
      responses:
        '200':
          description: List of tasks for the authenticated user
        '401':
          $ref: '#/components/responses/UnauthorizedError'
    post:
      tags: [Tasks]
      summary: Create task (JWT required)
      security: [{ BearerAuth: [] }]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
      responses:
        '201':
          description: Task created for authenticated user
        '401':
          $ref: '#/components/responses/UnauthorizedError'

  /api/tasks/{id}:
    get:
      tags: [Tasks]
      summary: Get task by ID (JWT + ownership)
      security: [{ BearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Task for authenticated user }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '403': { $ref: '#/components/responses/ForbiddenError' }
        '404': { $ref: '#/components/responses/NotFoundError' }
    put:
      tags: [Tasks]
      summary: Update task (JWT + ownership)
      security: [{ BearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200': { description: Task updated }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '403': { $ref: '#/components/responses/ForbiddenError' }
        '404': { $ref: '#/components/responses/NotFoundError' }
    delete:
      tags: [Tasks]
      summary: Delete task (JWT + ownership)
      security: [{ BearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '204': { description: Task deleted }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '403': { $ref: '#/components/responses/ForbiddenError' }
        '404': { $ref: '#/components/responses/NotFoundError' }

  /api/tasks/{id}/complete:
    patch:
      tags: [Tasks]
      summary: Toggle completion (JWT + ownership)
      security: [{ BearerAuth: [] }]
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200': { description: Task toggled }
        '401': { $ref: '#/components/responses/UnauthorizedError' }
        '403': { $ref: '#/components/responses/ForbiddenError' }
        '404': { $ref: '#/components/responses/NotFoundError' }

components:
  schemas:
    TaskCreate:
      type: object
      required: [title]
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          nullable: true
          maxLength: 1000
    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
        description:
          type: string
          nullable: true
          maxLength: 1000
