openapi: 3.1.0
info:
  title: Todo API - Backend Foundation
  description: REST API for managing todo tasks (without authentication in Feature 1)
  version: 1.0.0
  contact:
    name: Phase 2 - Backend API Foundation
    url: https://github.com/phase-2

servers:
  - url: http://localhost:8000
    description: Local development server
  - url: https://api.example.com
    description: Production server (TBD)

tags:
  - name: Health
    description: System health and status endpoints
  - name: Tasks
    description: Task CRUD operations

paths:
  /health:
    get:
      tags:
        - Health
      summary: Health Check
      description: Check API and database connectivity status
      operationId: healthCheck
      responses:
        '200':
          description: System is healthy
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HealthResponse'
              example:
                status: "healthy"
                database: "connected"
                version: "1.0.0"
                timestamp: "2025-12-09T10:30:00Z"
        '503':
          description: System is unhealthy (database connection failed)
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Database connection failed"
                error_code: "DATABASE_UNAVAILABLE"

  /api/tasks:
    get:
      tags:
        - Tasks
      summary: List All Tasks
      description: Retrieve all tasks from the database (will be filtered by user in Feature 3)
      operationId: listTasks
      parameters:
        - name: completed
          in: query
          description: Filter by completion status
          required: false
          schema:
            type: boolean
            example: false
      responses:
        '200':
          description: List of tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: 1
                  user_id: "user-uuid-123"
                  title: "Buy groceries"
                  description: "Milk, eggs, bread"
                  completed: false
                  created_at: "2025-12-09T10:00:00Z"
                  updated_at: "2025-12-09T10:00:00Z"
                - id: 2
                  user_id: "user-uuid-123"
                  title: "Call dentist"
                  description: null
                  completed: true
                  created_at: "2025-12-08T14:30:00Z"
                  updated_at: "2025-12-09T09:15:00Z"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      tags:
        - Tasks
      summary: Create New Task
      description: Create a new task with title and optional description
      operationId: createTask
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            example:
              title: "Buy groceries"
              description: "Milk, eggs, bread"
              user_id: "user-uuid-123"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 3
                user_id: "user-uuid-123"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                created_at: "2025-12-09T10:30:00Z"
                updated_at: "2025-12-09T10:30:00Z"
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
              example:
                detail:
                  - loc: ["body", "title"]
                    msg: "field required"
                    type: "value_error.missing"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/tasks/{task_id}:
    get:
      tags:
        - Tasks
      summary: Get Task by ID
      description: Retrieve a specific task by its ID
      operationId: getTask
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Task found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: "user-uuid-123"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                created_at: "2025-12-09T10:00:00Z"
                updated_at: "2025-12-09T10:00:00Z"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Task 999 not found"
                error_code: "TASK_NOT_FOUND"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    put:
      tags:
        - Tasks
      summary: Update Task
      description: Update an existing task's title and/or description
      operationId: updateTask
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              title: "Buy groceries and fruits"
              description: "Milk, eggs, bread, apples, bananas"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: "user-uuid-123"
                title: "Buy groceries and fruits"
                description: "Milk, eggs, bread, apples, bananas"
                completed: false
                created_at: "2025-12-09T10:00:00Z"
                updated_at: "2025-12-09T11:30:00Z"
        '400':
          description: Invalid input data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ValidationErrorResponse'
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Task 999 not found"
                error_code: "TASK_NOT_FOUND"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      tags:
        - Tasks
      summary: Delete Task
      description: Remove a task from the database
      operationId: deleteTask
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Task deleted successfully (no content)
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Task 999 not found"
                error_code: "TASK_NOT_FOUND"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/tasks/{task_id}/complete:
    patch:
      tags:
        - Tasks
      summary: Toggle Task Completion
      description: Mark a task as complete or incomplete (toggle)
      operationId: toggleTaskCompletion
      parameters:
        - name: task_id
          in: path
          description: Task ID
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Task completion status toggled
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: 1
                user_id: "user-uuid-123"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: true
                created_at: "2025-12-09T10:00:00Z"
                updated_at: "2025-12-09T11:45:00Z"
        '404':
          description: Task not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                detail: "Task 999 not found"
                error_code: "TASK_NOT_FOUND"
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: integer
          description: Task unique identifier
          example: 1
        user_id:
          type: string
          description: User ID who owns the task
          example: "user-uuid-123"
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Task description (optional)
          example: "Milk, eggs, bread"
        completed:
          type: boolean
          description: Task completion status
          example: false
        created_at:
          type: string
          format: date-time
          description: Task creation timestamp (ISO 8601 UTC)
          example: "2025-12-09T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (ISO 8601 UTC)
          example: "2025-12-09T10:00:00Z"

    TaskCreate:
      type: object
      required:
        - title
        - user_id
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Task title (required)
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Task description (optional)
          example: "Milk, eggs, bread"
        user_id:
          type: string
          description: User ID (required for Feature 1, will be from JWT in Feature 3)
          example: "user-uuid-123"

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 200
          description: Updated task title (optional)
          example: "Buy groceries and fruits"
        description:
          type: string
          nullable: true
          maxLength: 1000
          description: Updated task description (optional)
          example: "Milk, eggs, bread, apples, bananas"

    HealthResponse:
      type: object
      required:
        - status
        - database
        - version
        - timestamp
      properties:
        status:
          type: string
          enum: [healthy, unhealthy]
          description: Overall system status
          example: "healthy"
        database:
          type: string
          enum: [connected, disconnected]
          description: Database connection status
          example: "connected"
        version:
          type: string
          description: API version
          example: "1.0.0"
        timestamp:
          type: string
          format: date-time
          description: Health check timestamp (ISO 8601 UTC)
          example: "2025-12-09T10:30:00Z"

    ErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Human-readable error message
          example: "Task not found"
        error_code:
          type: string
          description: Machine-readable error code
          example: "TASK_NOT_FOUND"

    ValidationErrorResponse:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          description: List of validation errors
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of the error (e.g., ["body", "title"])
                example: ["body", "title"]
              msg:
                type: string
                description: Error message
                example: "field required"
              type:
                type: string
                description: Error type
                example: "value_error.missing"
          example:
            - loc: ["body", "title"]
              msg: "field required"
              type: "value_error.missing"

