"""
Task Model Module

Defines the Task data structure and validation logic.
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Optional


@dataclass
class Task:
    """
    Represents a single todo task.
    
    Attributes:
        id: Unique identifier (auto-generated by TaskManager)
        title: Task title (1-200 characters, required)
        description: Task description (max 1000 characters, optional)
        completed: Completion status (default: False)
        created_at: Timestamp when task was created (auto-generated)
    """
    
    id: int
    title: str
    description: str = ""
    completed: bool = False
    created_at: datetime = field(default_factory=datetime.now)
    
    def __post_init__(self) -> None:
        """
        Validate task data after initialization.
        
        Raises:
            ValueError: If title or description validation fails
        """
        # Validate title
        if not self.title or len(self.title.strip()) == 0:
            raise ValueError("Title cannot be empty")
        if len(self.title) > 200:
            raise ValueError("Title too long (max 200 characters)")
        
        # Validate description
        if len(self.description) > 1000:
            raise ValueError("Description too long (max 1000 characters)")
        
        # Trim whitespace
        self.title = self.title.strip()
        self.description = self.description.strip()
    
    def __str__(self) -> str:
        """Return string representation of task."""
        status = "✓" if self.completed else "○"
        return f"[{status}] {self.id}. {self.title}"
    
    def to_dict(self) -> dict:
        """
        Convert task to dictionary.
        
        Returns:
            Dictionary representation of the task
        """
        return {
            "id": self.id,
            "title": self.title,
            "description": self.description,
            "completed": self.completed,
            "created_at": self.created_at.isoformat()
        }

